// <auto-generated />
using System;
using AiCv.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiCv.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiCv.Api.Modules.Opportunities.Entities.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JobOffers");
                });

            modelBuilder.Entity("AiCv.Api.Modules.Opportunities.Entities.JobOfferAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedContractType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedExperienceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedTechnologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedResponsibilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawAnalysisJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId")
                        .IsUnique();

                    b.ToTable("JobOfferAnalyses");
                });

            modelBuilder.Entity("AiCv.Api.Modules.Profiles.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("AiCv.Api.Modules.Profiles.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AiCv.Api.Modules.Opportunities.Entities.JobOffer", b =>
                {
                    b.HasOne("AiCv.Api.Modules.Profiles.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiCv.Api.Modules.Opportunities.Entities.JobOfferAnalysis", b =>
                {
                    b.HasOne("AiCv.Api.Modules.Opportunities.Entities.JobOffer", "JobOffer")
                        .WithOne("Analysis")
                        .HasForeignKey("AiCv.Api.Modules.Opportunities.Entities.JobOfferAnalysis", "JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("AiCv.Api.Modules.Profiles.Entities.Profile", b =>
                {
                    b.HasOne("AiCv.Api.Modules.Profiles.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("AiCv.Api.Modules.Profiles.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiCv.Api.Modules.Opportunities.Entities.JobOffer", b =>
                {
                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("AiCv.Api.Modules.Profiles.Entities.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
