// <auto-generated />
using System;
using AiCv.OpportunityService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiCv.OpportunityService.Data.Migrations
{
    [DbContext(typeof(OpportunityDbContext))]
    partial class OpportunityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiCv.OpportunityService.Modules.Opportunities.Entities.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JobOffers");
                });

            modelBuilder.Entity("AiCv.OpportunityService.Modules.Opportunities.Entities.JobOfferAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CandidateRisks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvFocusPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedContractType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedExperienceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetectedTechnologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedResponsibilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtractedSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uuid");

                    b.Property<int>("MatchScoreEstimation")
                        .HasColumnType("integer");

                    b.Property<string>("MustHaveRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NiceToHaveRequirements")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawAnalysisJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasoningSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId")
                        .IsUnique();

                    b.ToTable("JobOfferAnalyses");
                });

            modelBuilder.Entity("AiCv.OpportunityService.Modules.Opportunities.Entities.OpportunityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AiCv.OpportunityService.Modules.Opportunities.Entities.JobOffer", b =>
                {
                    b.HasOne("AiCv.OpportunityService.Modules.Opportunities.Entities.OpportunityUser", "User")
                        .WithMany("JobOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiCv.OpportunityService.Modules.Opportunities.Entities.JobOfferAnalysis", b =>
                {
                    b.HasOne("AiCv.OpportunityService.Modules.Opportunities.Entities.JobOffer", "JobOffer")
                        .WithOne("Analysis")
                        .HasForeignKey("AiCv.OpportunityService.Modules.Opportunities.Entities.JobOfferAnalysis", "JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("AiCv.OpportunityService.Modules.Opportunities.Entities.JobOffer", b =>
                {
                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("AiCv.OpportunityService.Modules.Opportunities.Entities.OpportunityUser", b =>
                {
                    b.Navigation("JobOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
