// <auto-generated />
using System;
using AiCv.CvService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiCv.CvService.Data.Migrations
{
    [DbContext(typeof(CvDbContext))]
    [Migration("20260601211518_AddCvPdfObjectStorageMetadata")]
    partial class AddCvPdfObjectStorageMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiCv.CvService.Modules.Cvs.Entities.GeneratedCv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetContentType")
                        .HasColumnType("text");

                    b.Property<string>("AssetFileName")
                        .HasColumnType("text");

                    b.Property<long?>("AssetSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfBucketName")
                        .HasColumnType("text");

                    b.Property<string>("PdfObjectKey")
                        .HasColumnType("text");

                    b.Property<long?>("PdfSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfessionalSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeycloakId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("GeneratedCvs");
                });
#pragma warning restore 612, 618
        }
    }
}
